### POST request to create new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "gender": "MALE",
  "firstname": "Florian",
  "lastname": "Cowper",
  "birthDate": "1994-08-28",
  "phoneNumbers": [
    {
      "number": "+49 152 759406",
      "type": "MOBILE"
    }
  ],
  "email": "kafka_test@test.com",
  "street": "Konrad-Zuse-Str. 19",
  "zipCode": "99099",
  "city": "Erfurt"
}

###