### POST request to create new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "gender": "FEMALE",
  "firstname": "Vanessa",
  "lastname": "Bauer",
  "birthDate": "1989-11-03",
  "phoneNumbers": [
    {
      "number": "+49 911 834693564",
      "type": "PRIVATE"
    },
    {
      "number": "+49 173 637477",
      "type": "MOBILE"
    }
  ],
  "email": "billing.service@test.com",
  "street": "Dominion Strasse 4",
  "zipCode": "90874",
  "city": "Nuremberg"
}

###